# @host = https://epiploic-temperance-unwhimperingly.ngrok-free.dev/api
@host = http://localhost:3000/api

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZTAyMDhiYy05YjI3LTQzNjUtYTFkYS0wYjVmODkzZDI0MGMiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYyMjIxNTQzLCJleHAiOjE3NjIyMjE1NDh9.cKRGTlHg_-hzEeYbU_34k9ELNRmFey5OQllUpLkja0M

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Mjc3OTUyOS1mYWRjLTRkZDEtYWU2OS0zNjkxNmFjNzRiZTciLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJ0b2tlbklkIjoiZDQ4MzFiMzUtZGIwOC00ZmM4LTgwZTItNzFjNGJiYTc3Y2JjIiwiaWF0IjoxNzYyMjM1MTU0LCJleHAiOjE3NjI4Mzk5NTR9.Gg0cAIty0kmmwPKwi1vr3o_m3ZB9VRjGihQ_ULkg9NY


#######################################
##               Auth               ##
######################################

###
POST {{host}}/auth/sign-up
Content-Type: application/json

{
	"email": "test@example.com",
	"password": "testpass",
	"firstName": "Test",
	"lastName": "User"
}

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
	"email": "test@example.com",
	"password": "testpass"
}

###
POST {{host}}/auth/refresh-token
Authorization: Bearer {{refreshToken}}

###
POST {{host}}/auth/sign-out
Authorization: Bearer {{refreshToken}}

#######################################
##              Twilio              ##
######################################

###
GET {{host}}/twilio/token

#######################################
##              Clients              ##
#######################################

###
POST {{host}}/clients
Content-Type: application/json

{
	"name": "New Client3",
	"email": "client3@test.com",
	"contactPerson": "Jeff2",
	"businessName": "Client Business2",
	"phoneNumber": "+1234567890"
}
###
GET {{host}}/clients

#######################################
##             Campaigns             ##
#######################################

###
GET {{host}}/campaigns/

###
GET {{host}}/campaigns?unassignedFlow=true

###
GET {{host}}/campaigns/7452cd4f-7e25-4077-85a8-db8465def1f2

###
POST {{host}}/campaigns/
Content-Type: application/json

{
	"name": "New Campaign",
	"description": "Description of the new campaign",
	"startDate": "2024-01-01T00:00:00Z",
	"endDate": "2024-12-31T23:59:59Z",
	"clientId": "7749f6e7-5b07-49c2-8890-5d2736776463"
}

###
PATCH {{host}}/campaigns/19395bd8-13db-4f2f-a519-567889e7f4a3
Content-Type: application/json

{
	"flowId": "47c0d081-79d7-492b-b39d-d396a2f6f95b"
}

###
GET {{host}}/campaigns/


#####################################
##              Users              ##
#####################################

###
GET {{host}}/users

###
GET {{host}}/users/9ddab346-07b9-4b0e-a39d-368aa2369762?includeUnassignedClients=true

###
PATCH {{host}}/users/15f7650d-8c01-45c5-bbd4-27480d720504
Content-Type: application/json

{
	"clientIds": ["client1", "client2", "client3"]
}


##################################
##         User Clients         ##
##################################

###
GET {{host}}/user-clients



###################################
##             Flows             ##
###################################
###
POST {{host}}/flows
Content-Type: application/json

{
	"name": "New Flow",
	"steps": [
		{
			"name": "Step 1",
			"order": 1,
			"activities": [
				"52daf5f0-46d8-4695-b248-4fb7765e0008",
				"54eda8d9-5b1c-4186-932b-750d1af48069"
			]
		}
	]
}

###
POST {{host}}/flows
Content-Type: application/json

{
	"name": "New Flow",
	"steps": [
		{
			"name": "Step 1",
			"order": 1
		}
	]
}

###
GET {{host}}/flows



#####################
## Flow Activities ##
#####################


###
POST {{host}}/flow-activities
Content-Type: application/json

{
	"name": "Webhook",
	"type": "webhook"
}

###
GET {{host}}/flow-activities
#endregion