# @host = https://epiploic-temperance-unwhimperingly.ngrok-free.dev/api
@host = http://localhost:3000/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTIyNjhiZC1lZjJmLTQzMWEtOGM4Zi02YTE1Nzg1ZWEyMTkiLCJlbWFpbCI6ImFudGhvbnluYXVpQGdtYWlsLmNvbSIsInJvbGVzIjpbImVtcGxveWVlIl0sImlhdCI6MTc2MzIwOTUwOSwiZXhwIjoxNzYzMjk1OTA5fQ.vPgEMH0yPMyCMUyhpPDjRZ52cEIrgbgarSfabDc7QbI
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYWEyMDcyMy1hOGVhLTRmNzEtODkwNC0xMWY5MTg3NjQxNGIiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJ0b2tlbklkIjoiOGNmNTBmYTMtNmUzYy00Mjc1LWFlYWUtM2VhMDkyYjI1YjE4IiwiaWF0IjoxNzYyNTg3NjY2LCJleHAiOjE3NjMxOTI0NjZ9.vzqlsDXfmKj0Tea3d8UX_opESgWk2hD4NJiXUviA2Xs


######################################
##               Auth               ##
######################################

###
POST {{host}}/auth/sign-up
Content-Type: application/json

{
	"email": "test@example.com",
	"password": "testpass",
	"firstName": "Test",
	"lastName": "User"
}

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
	"email": "anthonynaui@gmail.com",
	"password": "Test123Test123"
}

###
POST {{host}}/auth/refresh-token
Authorization: Bearer {{refreshToken}}

###
POST {{host}}/auth/sign-out
Authorization: Bearer {{refreshToken}}

###
GET {{host}}/auth
Authorization: Bearer {{accessToken}}

#######################################
##              Twilio              ##
######################################

###
GET {{host}}/twilio/token

#######################################
##              Clients              ##
#######################################

###
POST {{host}}/clients
Content-Type: application/json

{
	"name": "New Client4",
	"email": "client4@test.com",
	"contactPerson": "Jeff2",
	"businessName": "Client Business2",
	"phoneNumber": "+1234567890",
	"contacts": [
		{"name": "Anthony Naui", "contactNumber": "+61493233059"},
		{"name": "Another Contact", "contactNumber": "+61493233060"}
	]
}
###
GET {{host}}/clients

#######################################
##             Campaigns             ##
#######################################

###
GET {{host}}/campaigns
Authorization: Bearer {{accessToken}}

###
GET {{host}}/campaigns?unassignedFlow=true

###
GET {{host}}/campaigns/47e53f6f-3058-4c00-a09b-809e2ea9d5b7

###
POST {{host}}/campaigns/
Content-Type: application/json

{
	"name": "New Campaign",
	"description": "Description of the new campaign",
	"startDate": "2024-01-01T00:00:00Z",
	"endDate": "2024-12-31T23:59:59Z",
	"clientId": "55d76013-32d4-4c5c-8c0d-c0467401291a"
}

###
PATCH {{host}}/campaigns/47e53f6f-3058-4c00-a09b-809e2ea9d5b7
Content-Type: application/json

{
	"flowId": "6279c50a-266a-4a2d-a8bc-803ac702b6c3"
}

###
GET {{host}}/campaigns/af52a19a-a029-4d3c-b7e8-5b7948668156


###
GET {{host}}/flows


#####################################
##              Users              ##
#####################################

###
GET {{host}}/users/2e2268bd-ef2f-431a-8c8f-6a15785ea219
Authorization: Bearer {{accessToken}}

###
POST {{host}}/users
Content-Type: application/json

{
	"firstName": "John",
	"lastName": "Doe",
	"email": "john.doe11@example.com",
	"password": "securePassword123"
}

###
PATCH {{host}}/users/b2f610a3-8731-45fc-835e-55b00f581599
Content-Type: application/json

{
	"firstName": "WEEEEE"
}

###
GET {{host}}/users/b8a9171a-4ec6-4920-ad8e-d928fa42b7a2?includeUnassignedClients=true

###
GET {{host}}/users/b8a9171a-4ec6-4920-ad8e-d928fa42b7a2?includeClients=true

###
PATCH {{host}}/users/15f7650d-8c01-45c5-bbd4-27480d720504
Content-Type: application/json

{
	"clientIds": ["client1", "client2", "client3"]
}


##################################
##         User Clients         ##
##################################

###
GET {{host}}/user-clients?userId=01ea5f0d-30bd-498f-94f0-cfc62d7103fe



###################################
##             Flows             ##
###################################

###
POST {{host}}/flows
Content-Type: application/json

{
	"name": "New Flow",
	"steps": [
		{
			"name": "Step 1",
			"order": 1,
			"activities": [
				"52daf5f0-46d8-4695-b248-4fb7765e0008",
				"54eda8d9-5b1c-4186-932b-750d1af48069"
			]
		}
	]
}

###
POST {{host}}/flows
Content-Type: application/json

{
	"name": "New Flow",
	"steps": [
		{
			"name": "Step 1",
			"order": 1
		}
	]
}

###
GET {{host}}/flows



#####################
## Flow Activities ##
#####################


###
POST {{host}}/flow-activities
Content-Type: application/json

{
	"name": "Webhook",
	"type": "webhook"
}

###
GET {{host}}/flow-activities?limit=10
#endregion

#################################################
##             Campaign Flow Steps             ##
#################################################

###
GET {{host}}/campaign-flow-steps


#############################################
##             Client Contacts             ##
#############################################

###
GET {{host}}/client-contacts

###
GET {{host}}/clients/3cf72497-df14-4f2a-8522-adebf10c8935
Authorization: Bearer {{accessToken}}

###
POST {{host}}/client-contacts
Content-Type: application/json

{
	"name": "Anthony Naui",
	"contactNumber": "+61493233059",
	"type": "mobile",	
	"clientIds": ["55d76013-32d4-4c5c-8c0d-c0467401291a"]
}

####################################################
##             Client Client Contacts             ##
####################################################

###
GET {{host}}/client-client-contacts


###################################
##  Campaign Contact Flow Steps  ##
###################################

###
GET {{host}}/campaign-contact-flow-steps